packages:
  - packages/*
  - example

catalogs:
  dev:
    '@types/node': ^24
    tsdown: ^0.18.0
    typescript: ^5.9.3
  react19:
    '@types/react': ^19
    '@types/react-dom': ^19
    react: ^19.2.3
    react-dom: ^19.2.3

onlyBuiltDependencies:
  - sharp
  - esbuild
